### ISSUE TITLE
Hacktoberfest 2017

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/conversations#14]
Should we take part in https://hacktoberfest.digitalocean.com/?

**Comment by tracykteal** [comment]
It would be really great to highlight github lesson contributions in this culture of open source contributions. Plus t-shirts.

**Comment by kariljordan** [comment]
Here are some of the Hacktober Fest activities we have done since this issue was opened:

- [Library Carpentry Hackathon a Great Success](https://carpentries.org/blog/2018/05/lc-sprint-report/)
- [Hacktoberfest 2020 - Glosario Contribution Drive](https://carpentries.org/blog/2020/10/hacktoberfest-2020-glosario/)
- [The Carpentries Tagathon - Our Hacktoberfest Initiative ](https://carpentries.org/blog/2019/10/carpentries-tagathon/)

We are discussing another round of Glosario contributions for Hacktober Fest 2021. Thanks so much for this idea. Closing this issue now, but feel free to reopen if you have more feedback.
