### ISSUE TITLE
Facilitating the community vs decision making

### ISSUE THREAD

**Issue by ctb** [carpentries/conversations#5]
I'm wondering about the role that the Carpentries leadership expects to play in managing the community vs facilitating the community & then cherry-picking ideas for their own focus? The messaging in #1 is slightly concerning -- "We want to give community members opportunities", "We know that we need effective ways for [...] Community members to propose ideas for new work or directions for ongoing work.", "Staff to jointly decide on priorities," "As we work to develop a communications strategy, Carpentry staff will actively monitor this repo..." In all of these, there's supervision and decision making going on by the Carpentry staff, but little to no explicit recognition of the goals and needs of the community of instructors.

On the one hand, Carpentry staff need an overall strategy (strategic goals, staff time to be devoted to..., guaranteed deliverables, maintenance guarantees, etc.) when engaging with "outside" entities.  On the other hand, it is limiting to apply only this kind of strategy to an open community, because you end up constraining the Carpentries to the bandwidth of the paid staff.  It's also a bit destructive because in the end the Carpentries depend massively on lesson development and delivery by largely unpaid volunteers, and without them we would have very little.  I'm already seeing that the paid staff are completely overwhelmed ;).

I don't have a strong conclusion, and I think the choice of language isn't intentional, but I do think it reflects an underlying perspective about the community that should be challenged. I would be happier with language that e.g. spoke of facilitating the instructor community, connecting the instructor community with partner needs, and supporting the Carpentry materials so that the instructor community can do a better job of delivery.  I'm certain this is compatible with the visions of @jduckles and @tracykteal, too.

A few random thoughts --

I'm most familiar with the Python community, where python-dev manages the development of the core Python language (with both formal and informal processes), the PSF manages the IP (trademarks, legal, accounting) and works with the community (organizing conferences and coordinating activities and supporting community activities), and a huge community (package developers, language users, and the like).  I don't know how well this can map on to the Carpentries, but it has some interesting parallels and divisions of labor.  For example, the PSF is involved in language development only inasmuch as there are people shared between python-dev and the PSF, but the formal processes of language development seem completely separate from the PSF staff.

I think the Carpentry staff can play an important (critical? required? :) role in mapping out processes (which they have already been doing over the last year or more!) and ensuring that they move towards openness (I see this as one of the goals of #1).

I see a lot of conference calls being made among the staff, and a lot of decisions being made on the conference calls (all anecdata, admittedly, but with a high number of anecdotal observations). This is antithetical to open community and I think connects with the question of what the role of the staff is vs what the potential role of the community.

More, the committee/phone call model is very academically inspired and top-down (maybe businesses operate this way, too?). It is not very open-source-y and limits casual participation in discussions, which limits creativitity.  It does look efficient, but I think it scales poorly and keeps people uninvolved in relevant conversations.  I would encourage minimizing phone calls as a way of maximizing openness.

Software Carpentry and Data Carpentry have very different governance structures, too, and I think this connects with how invited into conversations the community will eventually feel.  It would be nice to see a breakdown of who, exactly, makes what decisions with what feedback from whom; or, at least, a breakdown of the official bodies of each Carpentry and a short description of the role that they are supposed to play.  (For example, I'm on the Advisory Council, which hasn't met for ages and seems to have absolutely no practical advisory role; is this something that should be changed?)

Not all (very few!) instructors will be interested in participating in advancing lessons, assessment, etc in a community driven way. @tracykteal mentioned the idea of having a subcommunity that focuses on thinking outside the box in terms of technology evolution in the lessons, lesson delivery, and the like - something more freewheeling than a committee, open to crazy ideas and discussion of the interplay between teaching practice, tech, assessment, etc.  (See the 'python-ideas' mailing list for a version of this in the Python community focused on language development.) This is maybe one model for the evolution of the 'discuss' list, which, for all its flaws, was the flagship vehicle for Software Carpentry community.

If this more open direction is taken, one challenge for the Carpentries will be to align the staff and the community so that they don't diverge too far in goals - e.g. if crazy lesson development stuff happens, the staff could be involved in providing feedback as to whether this is something partners can be sold on. (Another way to do this is to simply make sure there are some partners involved in the crazy lesson development stuff.)

**Comment by wking** [comment]
On Tue, Dec 13, 2016 at 07:43:04AM -0800, C. Titus Brown wrote:
> I see a lot of conference calls being made among the staff, and a
> lot of decisions being made on the conference calls (all anecdata,
> admittedly, but with a high number of anecdotal observations). This
> is antithetical to open community and I think connects with the
> question of what the role of the staff is vs what the potential role
> of the community.

For a more formal (although mailing-list-centric) phrasing of this
idea, I like the Harvey Birdman Rule [1].  It also has a safety valve:

  Should such private communications nevertheless occur, participants
  in such communications are expected to publish summaries of any
  relevant discussions in a manner or medium accessible to the general
  net public.

> It would be nice to see a breakdown of who, exactly, makes what
> decisions with what feedback from whom…

I think more clarity over Steering Committee motions and minutes would
help here.  Do we have executive-branch decisions being made without a
leading motion (swcarpentry/board#140) or following minutes
(swcarpentry/board#116, swcarpentry/board#148)?

> … or, at least, a breakdown of the official bodies of each Carpentry
> and a short description of the role that they are supposed to play.

There's work in progress on this front (swcarpentry/board#144,
swcarpentry/board#146, swcarpentry/board#149).  More details on the
pan-carpentry structure (carpentries/bridge?) would be good, but it
sounds like those details are still being worked out [2].  Having
those details worked out in public would be nice :).

> If this more open direction is taken, one challenge for the
> Carpentries will be to align the staff and the community so that
> they don't diverge too far in goals - e.g. if crazy lesson
> development stuff happens, the staff could be involved in providing
> feedback as to whether this is something partners can be sold
> on. (Another way to do this is to simply make sure there are some
> partners involved in the crazy lesson development stuff.)

There's already a fairly detailed plan for landing new lessons [3].
I'm not wild about the $25k entry fee ($5k half-day lesson + $20k
hackathon), especially since in-person hackathons are a
high-commitment, synchronous development model which is much more
expensive than asynchronous, distributed development.  But entry-fee
aside, I don't see anything in the new-lesson plan that's
anti-openness.

And while the SWC FAQ has a number of requirements for our “core
topics” [4,5,…], I don't see any requirements for covering those
topics with one of the core lessons [6], so instructors at SWC-branded
workshops are free to experiment without waiting for a new lesson to
be officially accepted.

[1]: https://github.com/richardfontana/hbr/blob/master/HBR.md
[2]: https://github.com/swcarpentry/board/issues/146#issuecomment-265811330
[3]: https://github.com/swcarpentry/website/blob/df5d2e56899b6f523816603b8fbf7387b1e93edc/pages/lessons_incubation.md#2-what-new-lesson-proposals-need
[4]: https://software-carpentry.org/faq/#core-topics
[5]: https://software-carpentry.org/faq/#trademark
[6]: https://software-carpentry.org/lessons/

**Comment by jduckles** [comment]
@ctb I share many of your same concerns and really feel that the intent of moving conversations to a pan-carpentries repository was our first step in working out the different governance models and soliciting community involvement in the articulation of our shared futures together. The structure of the SWC Steering Committee is such that it places the community squarely in control through our elected steering committee being in control of the overall governance. This is not without its own structural problems (as currently implemented), but we can iteratively improve on those challenges over time.  The governance model of Data Carpentry is quite different, but the modes in which we all operate together are similar. 

We have an opportunity to articulate a vision of an umbrella governance structure that serves the community and applies staff time to enabling our learners, member organizations and instructors to have the capabilities and super powers they're looking for.

@wking, in the process of developing lessons I tend to lean toward aspiring for some version of Debian's social dynamics [1]. We want a way to build a system and interface for lesson contribution. We will expect things like, you use our lesson template, you follow some lesson dev guidelines (objectives, challenges, hands-on etc.), you demonstrate a community around your lesson (its being taught/used by people other than you). I agree that the "entry fee" is off-putting for some and I raised concerns about this tone in the drafts. I think the goal is to find a way to bring people together so that lessons aren't built in isolation. During my involvement in the hackathon for development of geospatial lessons [2] it was clear to me that good lessons need groups of people who are both experts and smart novices (they aren't experts in the topic at hand, but are senior community members) to help guide impactful and effective lesson development. If you can come up with a model for doing that asynchronously, or in a distributed fashion, we'd love to hear it.

[1] - https://www.debian.org/doc/manuals/maint-guide/start.en.html#socialdynamics
[2] - http://www.datacarpentry.org/lessons/#geospatial-data-workshop

**Comment by ctb** [comment]
@wking I'm happy to engage with you on specifics elsewhere, as needed; I intended the parent issue here to discuss issues with the vision, and tried to list out a few areas where there are or could be conflicts.  (I didn't want you to think I hadn't seen or appreciated your response! :)

**Comment by wking** [comment]
On Wed, Dec 14, 2016 at 10:21:15AM -0800, C. Titus Brown wrote:
> @wking I'm happy to engage with you on specifics elsewhere, as
> needed…

Sounds good.  I'll spin off (a)synchronous, distributed lesson
development into it's own issue later today.

> … I intended the parent issue here to discuss issues with the
> vision…

I think the general vision (“a thoughtful, efficient, and
community-driven communications strategy” [1] and a “commitment to
open and transparent communication” [2]) is a good, but the devil is
always in the details ;).  We already have some documented
requirements/procedures for SWC Steering Committee transparency [3].
It shouldn't be too hard to extend that transparency requirement to
cover other aspects of SWC governance; I think the main resistance
will be “we don't want transparency to be too much work” and that is
solvable.  We could do a better job executing the existing
requirements/procedures, but that's not a vision problem.

Issues like “should Carpentries decisions be made on conference
calls?” and “should we rephrase the messaging to focus on Carpentry
members write large (vs. staff/government)?” seem important, but don't
seem like vision problems.  Are there vision problems that are more
fundamental than how we express or implement the current open,
transparent, community-driven goals?

[1]: https://github.com/carpentries/conversations/blob/99a59dd9b2b7619e4c3ce4dcc11d8154a0d5b0e3/README.md
[2]: https://github.com/carpentries/conversations/issues/1#issue-195025541
[3]: https://github.com/swcarpentry/board/blame/73920cb2369b502d7780e4957943a809401925b3/governance.md#L32

**Comment by ctb** [comment]
@jduckles nails a big part of the problems I see by pointing out that SCF and
DC operate differently.  I think this is confusing and while I know it is being
tackled, it is very relevant to #1. I also know that DC (which is younger and
hence hasn't developed the same transparency guidelines or practice) has
more paid staff and hence is taking the lead in many ways, e.g. #1.

**Comment by ErinBecker** [comment]
@ctb - this is an important conversation to be having, so thank you for starting this issue. It's interesting how communication efforts can go awry.

My intention with my comments in #1 are largely to
1) Figure out how we can better facilitate interactions between community members so that they can do the work that they are excited to do and
2) Figure out ways to make it easier for community members to communicate with us (staff) about what they see as important work, so that we can effectively structure our time to best meet the needs of the community. 

It seems like much of this got lost in communication, but I hope we can agree that these are important and worthwhile goals. Hopefully the community will engage with us in helping to realize these goals.

**Comment by wking** [comment]
On Wed, Dec 14, 2016 at 11:07:40AM -0800, C. Titus Brown wrote:
> @jduckles nails a big part of the problems I see by pointing out
> that SCF and DC operate differently.  I think this is confusing and
> while I know it is being tackled, it is very relevant to #1.

I'm not very clear on how DC operates.  Formal pan-carpentry
collaboration (e.g. the shared Policy Subcommittee) seems new-ish, and
before that it didn't really matter (as far as SWC was concerned) how
DC operated.  As long as the SWC Steering Committee is going through
it's usual process for managing executive-branch action and publishing
its minutes, it shouldn't matter whether subcommittees and such are
pan-carpentry or SWC-only.

> I also know that DC (which is younger and hence hasn't developed the
> same transparency guidelines or practice) has more paid staff and
> hence is taking the lead in many ways, e.g. #1.

It's tempting to just go along with whatever your well-funded sibling
wants to do, but it's still up to the SWC Steering Committee to make
those decisions.  In the unlikely event that there are so many “let's
adopt $MOTION because DC suggests it, even though they haven't shared
its decision-making discussion” actions that people get upset, you can
fall back on the no-confidence petition [1].

The sticky point will be shared resources.  For example, who owns and
maintains this repo?  Does it fall under the SWC executive branch?
The DC executive branch?  Both (and then, what if they disagree)?  I
think the solution to that is just assign ownership to one Carpentry
(e.g. put this repo under DC), and have the other Carpentries ride
along as long as they find that convenient.  Using distributed tooling
(e.g. mailing lists, since all subscribers have copies of the
discussion) for this sort of thing helps avoid lock-in, but I doubt DC
(or whoever currently admins this repo) would pull the plug on the
repo without approval from the other Carpentries.

[1]: https://github.com/swcarpentry/board/blob/73920cb2369b502d7780e4957943a809401925b3/motion-of-no-confidence.md

**Comment by kariljordan** [comment]
Thank you everyone for your feedback on decision making in our open community. [#1](https://github.com/carpentries/conversations/issues/1#issuecomment-951238881) was recently closed as The Carpentries released a Communications Strategy in July 2019. You can find the strategy in our [handbook](https://docs.carpentries.org/topic_folders/communications/resources/comms-strategy.html#the-carpentries-communications-strategy).

Additionally, I invite you to read the post **_[On the governance of The Carpentries](https://carpentries.org/blog/2021/07/carpentries-governance/)_** which outlines and clarifies decision making from a governance (Executive Council) perspective.

[Core Team members](https://carpentries.org/team/) are individuals whose primary professional focus is to support the overall mission of The Carpentries on a daily basis. We do that through liaising with and supporting community roles and subgroups. Learn more about how the Core Team operates on [this page](https://carpentries.org/core-team-projects/).

Signed,
Kari L. Jordan (The Carpentries Executive Director)
Lex Nederbragt (Chair, The Carpentries Executive Council) @lexnederbragt
