### ISSUE TITLE
Revamping community calls

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/conversations#7]
Hi all,

I'd like to start a conversation about rethinking the format of our community calls. I was on a great ROpenSci community call this morning and really enjoyed the dialog they inspired from their community. What do you all think of revamping our community calls with some or all of the following ideas:

- Guest speakers - invited speakers to talk about a particular topic with Q&A following
- Blog posts - follow up blog posts summarizing the call and prompting more dialog around the issue
- Community contributed topics - polling the community a few months in advance to select or suggest a topic for upcoming community calls

I'd be very interested in hearing what folks think. If you don't normally attend community calls, would any of these make you more likely to attend? If you do normally attend, would these make community calls more exciting? What other suggestions do folks have about how to best engage our community on our community calls?

**Comment by stefaniebutland** [comment]
Erin,
You've identified some good key ideas that we're thinking about at rOpenSci too. 

We can work together to make sure we're not contributing to "community call fatigue", especially since our communities have a lot of overlap. Putting together a call with guest speakers on a topic is a lot of work so I wonder about the right frequency to balance value for effort.

Having our multiple lines of communication open with you and the Carpentries gives me confidence that we can help each other out and find that balance. Interested to know what your community tells you!

**Comment by ctb** [comment]
I enjoyed the call as well - as a presenter, everything went very smoothly!

Off the cuff thoughts,

- I feel like these are pretty much broadcast media, since it's awkward to have more than a few people participate in any meaningful way;
- recording them & then also summarizing briefly in a blog post really helps people who can't attend! and also makes them discoverable, all of which is good!
- I really like the idea of combining with several communities to make a talk series; if we can settle on times well in advance, I could e.g. host videos of these at my local institution for people interested in "open";

**Comment by kariljordan** [comment]
On December 19, 2018, we [introduced](https://carpentries.org/blog/2018/12/announcing-carpentries-community-discussions/) a new set of Community Discussions. Rather than offering one type of discussion that can accommodate only a few people at a time, we expanded the types of discussions, and the number of people that can attend. More information can be found in the [Community Discussions](https://docs.carpentries.org/topic_folders/instructor_development/community_discussions.html#community-discussions) section of our handbook. 

We launched [The Carpentries YouTube channel](https://www.youtube.com/thecarpentries) as the place to keep recorded community meetings. All recordings include closed captioning as well, and community members are encouraged to share a blog post with the outcomes of the call. To find posts from calls of interest you can search our [list of blog tags](https://carpentries.org/posts-by-tags/#top-of-page). 

Thank you all for your feedback on this issue. I believe I've addressed all of the recommendations and will close this issue now. Should you have any other feedback, please feel free to reopen this issue, get in touch with @acrall (The Carpentries Director of Community), and/or email community@carpentries.org.
